### ISSUE TITLE
Cannot find module 'ec-monitor'

### ISSUE THREAD

**Issue by werg** [error-central/error-central#13]
I followed the readme in branch `ec-to-cloud`, including this:
```(bash)
tixelbook@penguin:~/projects/error-central/vscode-extension$ npm link ec-monitor
/home/tixelbook/projects/error-central/vscode-extension/node_modules/ec-monitor -> /usr/lib/node_modules/ec-monitor -> /home/tixelbook/projects/error-central/ec-monitor
```

But then when starting up the extension it fails, any ideas?
(I ran `tsc --project .` on ec-monitor and `/out/ec-monitor.js` looks pretty normal)

```
Activating extension `error-central.error-central` failed:  Cannot find module 'ec-monitor'
Require stack:
- /home/tixelbook/projects/error-central/vscode-extension/out/extension.js
- /usr/share/code/resources/app/out/vs/loader.js
- /usr/share/code/resources/app/out/bootstrap-amd.js
- /usr/share/code/resources/app/out/bootstrap-fork.js
Here is the error stack:  Error: Cannot find module 'ec-monitor'
Require stack:
- /home/tixelbook/projects/error-central/vscode-extension/out/extension.js
- /usr/share/code/resources/app/out/vs/loader.js
- /usr/share/code/resources/app/out/bootstrap-amd.js
- /usr/share/code/resources/app/out/bootstrap-fork.js
	at Function._resolveFilename (internal/modules/cjs/loader.js:627:15)
	at Function.<anonymous> (internal/modules/cjs/loader.js:531:27)
	at Function.<anonymous> (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:796:719)
	at Function.<anonymous> (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:765:302)
	at Function._load (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:761:870)
	at Module.require (internal/modules/cjs/loader.js:685:19)
	at n (/usr/share/code/resources/app/out/vs/loader.js:15:524)
	at Object.<anonymous> (/home/tixelbook/projects/error-central/vscode-extension/out/extension.js:9:27)
	at Module._compile (/usr/share/code/resources/app/out/vs/loader.js:15:749)
	at Object..js (internal/modules/cjs/loader.js:798:10)
	at Module.load (internal/modules/cjs/loader.js:645:32)
	at Function.<anonymous> (internal/modules/cjs/loader.js:560:12)
	at Function.<anonymous> (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:796:719)
	at Function.<anonymous> (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:765:302)
	at Function._load (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:761:870)
	at Module.require (internal/modules/cjs/loader.js:685:19)
	at require (internal/modules/cjs/helpers.js:16:16)
	at Function.s [as __$__nodeRequire] (/usr/share/code/resources/app/out/vs/loader.js:32:963)
	at d._loadCommonJSModule (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:766:484)
	at d._doActivateExtension (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:677:300)
	at d._activateExtension (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:676:360)
	at Object.actualActivateExtension (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:674:296)
	at Object._activateExtension (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:506:21)
	at /usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:505:632
	at Array.map (<anonymous>)
	at Object._activateExtensions (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:505:620)
	at Object.activateByEvent (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:503:413)
	at d._activateByEvent (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:675:24)
	at /usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:683:293
```

**Comment by wanderingstan** [comment]
Seems to be a problem with not doing `npm install` on ec-monitor, or with doing `npm install` _before_ `npm link ecmonitor`. 

For me, fixed with https://github.com/error-central/error-central/commit/ea2199f0dba29e2757a11caebafa579e400bcd84

@werg please confirm if this fixes it for you!
