### ISSUE TITLE
Fails if docker daemon not running

### ISSUE THREAD

**Issue by wanderingstan** [error-central/error-central#8]
```
...
Now tailing /Users/stan/.ec/sessions/docker_hopcoin_storybook_1.out
extension.js:124
rejected promise not handled within 1 second: Error: Command failed: docker ps --format={{.Names}}, {{.CreatedAt}}
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

extensionHostProcess.js:775
stack trace: Error: Command failed: docker ps --format={{.Names}}, {{.CreatedAt}}
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

	at ChildProcess.exithandler (child_process.js:299:12)
	at ChildProcess.emit (events.js:182:13)
	at maybeClose (internal/child_process.js:962:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
```

**Comment by wanderingstan** [comment]
Should be fixed by https://github.com/error-central/error-central/pull/7/commits/a08bd3c03c6421875e9249a3af6ceefd2d3cdb08
